### ISSUE TITLE
pip shows deprecation notice when installing squad client from git

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad-client#100]
I installed a copy of `squad-client` using the following command and noted the following deprecation notice.

Installation:
```
pip install https://github.com/jscook2345/squad-client/archive/add-submit-tuxbuild-cmd.zip
```

Notice:
```
DEPRECATION: squad-client was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
```

This was because the `wheel` for `squad-client` could not be built:
```
Building wheels for collected packages: squad-client, pyrsistent
  Building wheel for squad-client (setup.py): started
  Building wheel for squad-client (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-cu3mevry/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-cu3mevry/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ujmod3pg
       cwd: /tmp/pip-req-build-cu3mevry/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-cu3mevry/setup.py", line 22, in <module>
      raise RuntimeError('Please use scripts/release to make releases!')
  RuntimeError: Please use scripts/release to make releases!
  ----------------------------------------
  ERROR: Failed building wheel for squad-client
```

**Comment by chaws** [comment]
Yeah, this is expected because [`setup.py`](https://github.com/Linaro/squad-client/blob/0.10.1/setup.py#L21) checks for `SQUAD_CLIENT_RELEASE` to prevent releases not made with `./script/release`. In your case you can just define it before running install.
