### ISSUE TITLE
Retry failed API calls

### ISSUE THREAD

**Issue by chaws** [Linaro/squad-client#160]
Occasionally, squad-client would make API calls to SQUAD and they'll fail. These might generate side effects on tools relying on squad-client, for instance, check the error below:

```
$ ./squad-report/scripts/squad-find-regressions \
  --group=lkft \
  --project=linux-stable-rc-linux-5.18.y \
  --build v5.18.9-103-g7622cfa48fbd \
  > regressions-v5.18.10-rc1.txt

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/ddiaz/devel/lkft-tools/bin/20220705/./squad-report/scripts/squad-find-regressions", line 96, in find_regression
    metadata=getid(test.metadata),
AttributeError: 'Test' object has no attribute 'metadata'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ddiaz/devel/lkft-tools/bin/20220705/./squad-report/scripts/squad-find-regressions", line 157, in <module>
    sys.exit(run())
  File "/home/ddiaz/devel/lkft-tools/bin/20220705/./squad-report/scripts/squad-find-regressions", line 154, in run
    p.map(find_regression, tests)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: 'Test' object has no attribute 'metadata'
```

Here, the `test.metadata` attribute didn't get fetched from the API, thus causing the crash. When re-running this script another time, it worked without any errors.

**Comment by chaws** [comment]
Fixed in https://github.com/Linaro/squad-client/pull/167
