### ISSUE TITLE
traceback when running tests

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad-client#75]
I installed `squad` from git master so it would include https://github.com/Linaro/squad/pull/881. After successfully installing that and the other items from `requirements-dev.txt`, I get the following traceback when I try to run the tests. It does not seem related to the work I'm doing.

```
❯ ./manage.py --debug --squad-host http://localhost:9000 test -v
[INFO] Running tests
[INFO] Starting a fresh squad instance on port 9000
[INFO] Creating database schema
[INFO] Applying tests/fixtures.py
[ERROR] Traceback (most recent call last):
  File "/Users/justin/GitHub/squad-client/.venv/bin/squad-admin", line 33, in <module>
    sys.exit(load_entry_point('squad==1.25.2', 'console_scripts', 'squad-admin')())
  File "/Users/justin/GitHub/squad-client/.venv/lib/python3.8/site-packages/squad/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/Users/justin/GitHub/squad-client/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/justin/GitHub/squad-client/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/justin/GitHub/squad-client/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/justin/GitHub/squad-client/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/justin/GitHub/squad-client/.venv/lib/python3.8/site-packages/django/core/management/commands/shell.py", line 92, in handle
    exec(sys.stdin.read())
  File "<string>", line 36, in <module>
  File "/Users/justin/GitHub/squad-client/.venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 668, in create
    return super(RelatedManager, self.db_manager(db)).create(**kwargs)
  File "/Users/justin/GitHub/squad-client/.venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/justin/GitHub/squad-client/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 420, in create
    obj = self.model(**kwargs)
  File "/Users/justin/GitHub/squad-client/.venv/lib/python3.8/site-packages/django/db/models/base.py", line 501, in __init__
    raise TypeError("%s() got an unexpected keyword argument '%s'" % (cls.__name__, kwarg))
TypeError: Test() got an unexpected keyword argument 'name'

Aborting tests!
[INFO] Terminating daemons
```

**Comment by mwasilew** [comment]
This might be an issue with fixtures that are outdated. @chaws could you take a look?

**Comment by chaws** [comment]
@mwasilew @jscook2345 they were outdated as well!

I opened this PR, and hoping to get a new one (for https://github.com/Linaro/squad-client/issues/72) in later today or early monday so I can make a new release
