### ISSUE TITLE
YAML missing when installing in local venv

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad-client#8]
Steps to reproduce:
 - clone the repository
 - create virtualenv 
```virtualenv -p python3 venv```
 - activate venv
```source venv/bin/activate```
 - install squad-client
```python setup.py install```
 - run ```manage.py```

```
./manage.py 
Traceback (most recent call last):
  File "./manage.py", line 3, in <module>
    from squad_client.manage import main
  File "/home/milosz/linaro/tcstorm/squad-client/squad_client/manage.py", line 8, in <module>
    from squad_client.commands import *
  File "/home/milosz/linaro/tcstorm/squad-client/squad_client/commands/report.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by chaws** [comment]
Good catch, I added that in Dockerfile, but didn't add to requirements.txt

**Comment by chaws** [comment]
Closed in https://github.com/Linaro/squad-client/pull/21
